services:
  backend:
    image: todo-backend
    pull_policy: never
    container_name: todo-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    ports:
      - "8000:8000"
  
  frontend:
    image: todo-frontend
    pull_policy: never
    container_name: todo-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
 